# Generated by Django 3.1.4 on 2020-12-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201218_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='description',
        ),
    ]
